<?php $this->headScript()->captureStart() ?>
    $(function(){
	var actionUrl = '<?= $this->url(array('controller' => 'api', 'action' => 'editcarvalidation',), 'default'); ?>';
	var formName = '<?= $this->editForm->getName() ?>';
	$(":input").on('blur', function(event) {
            var formElementId = $(this).attr('id');
            doValidation(formElementId, actionUrl, formName);
        });
    });
<?php $this->headScript()->captureEnd() ?>


<h1>Modifica Macchina</h1>
<?php if($this->error){ ?>

<div class="alert alert-danger"><h3><?=$this->error?></h3></div>
<a href="<?=$this->baseUrl($this->layout . '/catalog')?>">Indietro</a>
<?php } else { ?>
    <h4>Macchina:</h4>    
    <?=$this->editForm->render()?>
    <div align='center'> <a href="<?=$this->baseUrl($this->layout . '/catalog')?>">Indietro</a></div>
<?php } ?>