
<?php $this->headScript()->captureStart() ?>
    $(function(){
	var actionUrl = '<?= $this->url(array('controller' => 'api', 'action' => 'newcarvalidation',), 'default'); ?>';
	var formName = '<?= $this->macchinaForm->getName() ?>';
	$(":input").on('blur', function(event) {
            var formElementId = $(this).attr('id');
            doValidation(formElementId, actionUrl, formName);
        });
    });
<?php $this->headScript()->captureEnd() ?>




<div class="static">
 <h3>Aggiungi Macchina</h3>
 <p>Utilizza questa form per inserire una nuova macchina nel Catalogo</p>
  <?php echo $this->macchinaForm ?>
  <div align='center'> <a href="<?=$this->baseUrl($this->layout . '/catalog')?>">Indietro</a></div>
</div>