<html>
<table class="table">
  <thead>
    <tr>
        <th scope="col">Nome</th>
      <th scope="col">Cognome</th>
      <th scope="col">Marca</th>
      <th scope="col">Targa</th>
      <th scope="col">Inizio</th>
      <th scope="col">Fine</th>
    </tr>
  </thead>
  <tbody>
<?php foreach($this->nolList as $nl){ ?>
    <tr>
      <td><?=$nl->Nome?></td>
      <td><?=$nl->Cognome?></td>
      <td><?=$nl->Marca?></td>
      <td><?=$nl->TARGA?></td>
      <td><?=$nl->Inizio?></td>
      <td><?=$nl->Fine?></td>
    </tr>
</tbody>
<?php } ?>
</table>

</html>