<html>
<div align='right'>
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Seleziona mese &nbsp;
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'gennaio'),'default',true);?>">Gennaio</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'febbraio'),'default',true);?>">Febbraio</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'marzo'),'default',true);?>">Marzo</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'aprile'),'default',true);?>">Aprile</a></li>                                       
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'maggio'),'default',true);?>">Maggio</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'giugno'),'default',true);?>">Giugno</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'luglio'),'default',true);?>">Luglio</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'agosto'),'default',true);?>">Agosto</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'settembre'),'default',true);?>">Settembre</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'ottobre'),'default',true);?>">Ottobre</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'novembre'),'default',true);?>">Novembre</a></li>
    <li><a href="<?=$this->url(array('controller' => 'staff',
                                     'action' => 'noleggi',
                                     'm' => 'dicembre'),'default',true);?>">Dicembre</a></li>
                                                                                                                                                                                                    
  </ul></div>
<?php if($this->error){ ?>
<div align='center'>
<div class="alert alert-info"><h3><?=$this->error?></h3></div>
</div>
<?php } else { ?>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Cognome</th>
      <th scope="col">Marca</th>
      <th scope="col">Targa</th>
      <th scope="col">Inizio</th>
      <th scope="col">Fine</th>     
    </tr>
  </thead>
  <tbody>
<?php foreach($this->noleggiList as $i=>$nl){ ?>
    <tr>
      <td><?=($i+1)?></td>
      <td><?=$nl->Nome?></td>
      <td><?=$nl->Cognome?></td>
      <td><?=$nl->Marca?></td>
      <td><?=$nl->TARGA?></td>
      <td><?=date('d/m/Y', strtotime($nl->Inizio))?></td>
      <td><?=date('d/m/Y', strtotime($nl->Fine))?></td>
    </tr>
</tbody>
<?php }} ?>
</table>
</div>
</div>

</html>