<?php foreach($this->catalog as $car){ ?>

<table border style="border-collapse:collapse;">
    <tr><th rowspan="6"><?=$car->foto?></th><th>Zona</th><th>Prezzo</th></tr>
    <tr><td>Lorem</td><td><?=$car->prezzo?></td></tr>
    <tr><td>ipsum</td><td rowspan="2">25,50</td></tr>
    <tr><td>dolor</td></tr>
    <tr><td>sit</td><td  rowspan="2"><button type="button" onclick="alert('Hello world!')">Noleggia</button></td></td></tr>
    <tr><td>consectetur</td></tr>
</table>

<?php } ?>