<div align='right'>
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Ordina per &nbsp;
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
    <li><a href="#">prezzo: Crescente</a></li>
    <li><a href="#">prezzo: Decrescente</a></li>
    <li><a href="#">posti: Crescente</a></li>
    <li><a href="#">posti: Decrescente</a></li>
  </ul>
</div>
</div>


<?php foreach($this->catalog as $car){ ?>

<table border style="border-collapse:collapse;">
    <tr><th rowspan="6"><?=$car->foto?></th><th>Zona</th><th>Prezzo</th></tr>
    <tr><td>Lorem</td><td><?=$car->prezzo?></td></tr>
    <tr><td>ipsum</td><td rowspan="2">25,50</td></tr>
    <tr><td>dolor</td></tr>
    <tr><td>sit</td><td  rowspan="2"><button type="button" onclick="alert('Hello world!')">Noleggia</button></td></td></tr>
    <tr><td>consectetur</td></tr>
</table>

<?php } ?>

