<head>
    <style type="text/css">  
    div.split2{
    float: left;
    width: 50%;
    width: 49%;
    width: 50%;
    padding: 0 2%
    }   
    
    div.clearer{
    clear: left
    }
    </style>
</head>
<div align="center">
        <div class="split2">
            <h1><b>CONTATTACI</b></h1>                
            <ul class="list-group">
                <li class="list-group-item">Telefono Fisso: <a href="tel:+390123456789">071 1234567</a></li>
                <li class="list-group-item">Cellulare: <a href="tel:+390123456789">071 1234567</a></li>
                <li class="list-group-item">Email: <a href="mailto:gruppo12@gmail.info" title="Mandaci un messaggio">gruppo12@gmail.info</a></li>
                <li class="list-group-item">Facebook</li>
            </ul>
        </div>
    

    
    
    
    
        <div class="split2">
            <h1><b>DOVE SIAMO</b></h1>
            <ul class="list-group">
                <li class="list-group-item">Via Brecce Bianche, 12, 60131 </li>
                <li class="list-group-item">Ancona (AN)</li>
                <li class="list-group-item">Marche</li>
                <li class="list-group-item">altre sedi</li>
            </ul>        
        </div>
    <div class=”clearer”> </div>
</div>



<div align = "center">
    <iframe align = "middle" width="90%" height="525" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2889.948795942643!2d13.514406314877995!3d43.58678286474213!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132d80233dd931ef%3A0x161719e4f3f5daaf!2sUniversit%C3%A0+Politecnica+delle+Marche+-+Facolt%C3%A0+di+Ingegneria!5e0!3m2!1sit!2sit!4v1559761814942!5m2!1sit!2sit" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    <br><br>
    <p style="margin-bottom:20px;"><a href="https://www.google.it/maps/place/Universit%C3%A0+Politecnica+delle+Marche+-+Facolt%C3%A0+di+Ingegneria/@43.5867829,13.5144063,17z/data=!3m1!4b1!4m5!3m4!1s0x132d80233dd931ef:0x161719e4f3f5daaf!8m2!3d43.586779!4d13.516595?hl=it" target="_blank">CLICCA QUI PER VISUALIZZARE LA MAPPA INGRANDITA</a></p>  
</div>    

