<head>
    <style type="text/css">  
    div.split2{
    float: left;
    width: 50%;
    width: 49%;
    width: 50%;
    padding: 0 2%
    }   
    
    div.clearer{
    clear: left
    }
    </style>
</head>
<div align="center">
        <div class="split2">
            <h1>CONTATTACI</h1>
                <p>telefono fisso</p>
                <p>cellulare</p>
                <p>email</p>
                <p>facebook</p>
        </div>
        <div class="split2">
            <h1>DOVE SIAMO</h1>
                <p>via</p>
                <p>citta</p>
                <p>regione</p>
                <p>altre sedi</p>
        
        </div>
    <div class=”clearer”> </div>
</div>



<div align = "center">
    <iframe align = "middle" width="90%" height="525" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=Via+Brecce+Bianche,+12,+Ancona&amp;aq=0&amp;sll=41.442726,12.392578&amp;sspn=23.377375,53.657227&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Brecce+Bianche,+12,+60131+Ancona,+Marche&amp;z=14&amp;ll=43.581248,13.515684&amp;output=embed"></iframe><br /><small><a href="http://maps.google.it/maps?f=q&amp;source=embed&amp;hl=it&amp;geocode=&amp;q=Via+Brecce+Bianche,+12,+Ancona&amp;aq=0&amp;sll=41.442726,12.392578&amp;sspn=23.377375,53.657227&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Brecce+Bianche,+12,+60131+Ancona,+Marche&amp;z=14&amp;ll=43.581248,13.515684" style="color:#0000FF;text-align:left">Visualizzazione ingrandita della mappa</a></small>
</div>

