<h1 align='center'><b>FAQ's</b></h1>


<br>

<?php foreach($this->allFaqs as $faqs){?>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#<?=$faqs->ID?>" aria-expanded="false" aria-controls="collapseTwo">
          <?=$faqs->titolo?>
        </a>
          
      </h4>
    </div>
    <div id="<?=$faqs->ID?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
         <?=$faqs->testo?>
      </div>
    </div>
  </div>
</div>
<?php } ?>






