<h1 align="center">NOLEGGIA LA TUA AUTO!</h1>
<div>
    <p style='text-align: justify;'>
        Benvenuti nel nostro Autonoleggio. Siamo una delle compagnie di autonoleggio e mobilità leader nel mondo, e offre online 
        gli stessi servizi e la stessa qualità che potrete trovare nelle nostre agenzie: comodamente da casa, potrete noleggiare a 
        prezzi competitivi berline, SUV, station wagon, decappottabili e auto sportive per soddisfare ogni esigenza. Le più di 
        2000 stazioni di autonoleggio della nostra azienda in Italia e nel mondo offrono servizi aggiuntivi, come la possibilità 
        di noleggiare furgoni, pulmini e minivan. Sia che abbiate bisogno di noleggiare un'auto o un furgone, la nostra azienda 
        è sempre pronta a venire incontro alle vostre necessità con offerte vantaggiose, su internet come nelle nostre stazioni di 
        noleggio. 
        Per quanto il nostro servizio sia principalmente rivolto ai viaggi a breve termine per privati ed aziende, mettiamo a 
        disposizione anche vantaggiose tariffe per i noleggi a lungo termine. Le nostre coperture sono flessibili, e la 
        prenotazione online non presenta costi nascosti o aggiuntivi o sovrapprezzi. Consigliamo di visitare le nostre sezioni
        FAQ e Regolamento o, per ulteriiri chiarimenti, potete contattare l'amministratore con il nostro servizion di chat, o 
        potete contattare il nostro staff tramite e-mail. 
        Confronta e scopri le differenti categorie di auto a disposizione, che variano da località a località ma sono accomunate da 
        qualità premium e un'età media inferiore ai 12 mesi. Cerca, confronta e risparmia prenotando direttamente online!
    </p>
</div>

<br>

<div align="center">
    <form style="border:#000000 double 4px; width:400pt; padding:5px;" action="" align="center">
        <legend>RICERCA RAPIDA</legend>
            <p>
                <label>Marca <input name="marca" type="text" size="15"></label>
            </p>
            <p>
                <label style="margin-right: 1em;">Prezzo da: € <input name="prezzoMin" type="text" size="5"></label> 
                <label> a: € <input name="prezzoMax" type="text" size="5"></label>
            </p>
            <p>
                <label>Allestimento <input name="allestimento" type="text" size="25"></label>               
            </p>
            <p>
                <input type="submit" value="Cerca">
                <input type="reset" value="Azzera"> 
            </p>
        </form>
    
</div>

<br><br><br>

<h2 style="text-align: center;">GUIDA ALL'USO</h2>
    <div align="center">
        <h3>STEP 1</h3>
        <p><i class="fas fa-arrow-down" style="font-size: 4em;"></i></p>
        <h3>STEP 2</h3>
        <p><i class="fas fa-arrow-down" style="font-size: 4em;"></i></p>
        <h3>STEP 3</h3>
        <p><i class="fas fa-arrow-down" style="font-size: 4em;"></i></p>
        <h3>STEP 4</h3>
    </div>