<html>

<div align="center">
<form>
  <div class="form-group">
    <label for="InputEmail1">Email address</label>
    <input name="loginEmail" type="email" class="form-control" id="InputEmail" aria-describedby="email" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">La tua email non verrà mai condivisa con nessuno.</small>
  </div>
  <div class="form-group">
    <label for="InputPassword1">Password</label>
    <input name="loginPassword" type="password" class="form-control" id="InputPassword" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Non sono un robot</label>
  </div>
  <button type="submit" class="btn btn-primary">Accedi</button><button type="submit" class="btn btn-primary">Reset</button>
</form>
</div>

</html>