<?php $this->headScript()->captureStart() ?>
    $(function(){
	var actionUrl = '<?= $this->url(array('controller' => 'api', 'action' => 'loginvalidation',), 'default'); ?>';
	var formName = '<?= $this->loginForm->getName() ?>';
	$(":input").on('blur', function(event) {
            var formElementId = $(this).attr('id');
            doValidation(formElementId, actionUrl, formName);
        });
    });
<?php $this->headScript()->captureEnd() ?>

<html>

<div align="center">
  <?=$this->loginForm->render()?>
  <?php if($this->loginError){ ?>
    <div class="alert alert-danger" role="alert">Nome Utente o Password Errati!</div>
  <?php } ?>

  <a href="<?=$this->baseUrl('public/signin')?>">Non sei registrato? Clicca qui!</a>
</div>

</html>