<html>

<form class="needs-validation" novalidate>
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <label for="validationCustom01">Nome</label>
      <input type="text" class="form-control" id="validationCustom01" placeholder="Nome" required>

    </div>
    <div class="col-md-4 mb-3">
      <label for="validationCustom02">Cognome</label>
      <input type="text" class="form-control" id="validationCustom02" placeholder="Cognome"  required>

    </div>
    <div class="col-md-4 mb-3">
      <label for="validationCustomUsername">Username</label>
      <div class="input-group">
        <div class="input-group-prepend">

        </div>
        <input type="text" class="form-control" id="validationCustomUsername" placeholder="Username" aria-describedby="inputGroupPrepend" required>

      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-6 mb-3">
      <label for="validationCustom03">Città</label>
      <input type="text" class="form-control" id="validationCustom03"  required>

    </div>
    <div class="col-md-3 mb-3">
      <label for="validationCustom04">Stato</label>
      <input type="text" class="form-control" id="validationCustom04"  required>

    </div>
    <div class="col-md-3 mb-3">
      <label for="validationCustom05">Codice postale</label>
      <input type="text" class="form-control" id="validationCustom05"  required>

    </div>
  </div>


  <div class="form-group">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
      <label class="form-check-label" for="invalidCheck">
        Accetta termini e condizioni
      </label>

    </div>
  </div>
  <button class="btn btn-primary" type="submit">Registrazione</button>
</form>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>
</html>