<?php $this->headScript()->captureStart() ?>
    $(function(){
	var actionUrl = '<?= $this->url(array('controller' => 'api', 'action' => 'signinvalidation',), 'default'); ?>';
	var formName = '<?= $this->signinForm->getName() ?>';
	$(":input").on('blur', function(event) {
            var formElementId = $(this).attr('id');
            doValidation(formElementId, actionUrl, formName);
        });
    });
<?php $this->headScript()->captureEnd() ?>

<div align="center">
  <?=$this->signinForm->render()?>
  <?php if($this->error){ ?>
    <div class="alert alert-danger" role="alert"><?=$this->error?></div>
  <?php } ?>

  <a href="<?=$this->baseUrl('public/login')?>">Sei già registrato? Clicca qui!</a>
</div>
