<li><a href="<?=$this->baseUrl($this->layout . '/' . $this->app->url->aboutus)?>"><i class="fas fa-address-card"></i> Chi Siamo</a></li>
<li><a href="<?=$this->baseUrl($this->layout . '/' . $this->app->url->contacts)?>"><i class="fas fa-envelope-open-text"></i> Contattaci</a></li>
<li><a href="<?=$this->baseUrl($this->layout . '/' . $this->app->url->rules)?>"><i class="fas fa-book"></i> Regolamento</a></li>
<li><a href="<?=$this->baseUrl($this->layout . '/' . $this->app->url->faq)?>"><i class="fas fa-question"></i> Faq</a></li>