<li><a href="<?=$this->baseUrl($this->layout . '/' . $this->app->url->home)?>"><i class="fas fa-home"></i> Home</a></li>
<li><a href="<?=$this->baseUrl($this->layout . '/' . $this->app->url->catalog)?>"><i class="fas fa-car"></i> Catalogo</a></li>
<li><a href=""><i class="fas fa-user"></i> <?= $this->user->Username?></a></li>
<li><a href="<?=$this->baseUrl('public/logout')?>"><i class="fas fa-sign-out-alt"></i> Esci</a></li>