<div class="app-messanger">
    <div class="app-messanger-chat">
        <h3 class="app-messanger-talking">Amministratore</h3>
        <div class="app-messanger-chat-container"></div>
        <div class="app-messanger-chat-senders"></div>

        <textarea></textarea>
        <button type="submit" value="invia" class="btn btn-info">Invia</button>
    </div>
    <i class="fas fa-comment-dots app-messanger-icon" id="app-messanger-toggle"></i>
</div>