<div class="app-messanger">
    <div class="app-messanger-chat">
        <h3>Amministratore</h3>
        <div class="app-messanger-chat-container">
            <p class="app-messanger-message app-messanger-message-incoming">messaggio dall'amministratore 1</p>
            <p class="app-messanger-message app-messanger-message-outgoing">messaggio dall'utente 1</p>
            <p class="app-messanger-message app-messanger-message-incoming">messaggio dall'amministratore 2</p>
            <p class="app-messanger-message app-messanger-message-incoming">messaggio dall'amministratore 3</p>
            <p class="app-messanger-message app-messanger-message-outgoing">messaggio dall'utente 2</p>
            <p class="app-messanger-message app-messanger-message-outgoing">messaggio dall'utente 3</p>
            <p class="app-messanger-message app-messanger-message-incoming">messaggio dall'amministratore 4</p>
            <p class="app-messanger-message app-messanger-message-incoming">messaggio dall'amministratore 5</p>
            <p class="app-messanger-message app-messanger-message-incoming">messaggio dall'amministratore 6</p>
            <p class="app-messanger-message app-messanger-message-incoming">messaggio dall'amministratore 7</p>
        </div>

        <textarea></textarea>
        <button type="submit" value="invia" class="btn btn-info">Invia</button>
    </div>
    <i class="fas fa-comment-dots app-messanger-icon" id="app-messanger-toggle"></i>
</div>