<?= $this->doctype();?>

<html>
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headTitle(); ?>
        <?= $this->headScript(); ?>
    </head>
    <body>
        
    <nav class="navbar navbar-inverse" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?=$this->baseUrl('')?>">
                        <img src="<?=$this->baseUrl($this->app->image->brand)?>" alt="Car Rental" />
                    </a>
                    <p class="navbar-text app-brand-text"><a href="<?=$this->baseUrl('')?>"><?=$this->app->NomeAzienda?></a></p>
                </div>

                <div class="">
                    <ul class="nav navbar-nav navbar-right">
                        <?=$this->render('_header.' . $this->layout . '.phtml')?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="app-content"><?=$this->layout()->content;?></div>

        <div class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-center">
                        <?=$this->render('_footer.phtml')?>
                    </ul>
                </div>
            </div>
    </nav>

        <?php if($this->layout != 'public'){ echo $this->render('_messanger.phtml'); } ?>
    </body>
</html>