<?= $this->doctype();?>

<html>
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headTitle(); ?>
        <?= $this->headScript(); ?>
    </head>
    <body>
        
    <div class="navbar navbar-default app-header">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                            aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->baseUrl('')?>">
                        <img src="<?=$this->baseUrl($this->app->image->brand)?>" alt="Car Rental" />
                    </a>
                    <p class="navbar-text app-brand-text"><a href="<?=$this->baseUrl('')?>"><?=$this->app->NomeAzienda?></a></p>
                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <?=$this->render('_header.' . $this->layout . '.phtml')?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="app-content"><?=$this->layout()->content;?></div>

        <div class="navbar navbar-default app-footer">
            <div class="container-fluid">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <?=$this->render('_footer.phtml')?>
                    </ul>
                </div>
            </div>
        </div>

        <?php if($this->layout != 'public'){ echo $this->render('_messanger.phtml'); } ?>
    </body>
</html>