<?= $this->doctype();?>

<html>
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headTitle(); ?>
        <?= $this->headScript(); ?>
    </head>
    <body>
        
    <div class="navbar navbar-default app-header">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                            aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <img src="<?=$this->baseUrl('images/Brand.png')?>" alt="Car Rental" />
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?=$this->baseUrl('public')?>">Home</a></li>
                        <li><a href="<?=$this->baseUrl('public/aboutus')?>">Chi Siamo</a></li>
                        <li><a href="<?=$this->baseUrl('public/contacts')?>">Contattaci</a></li>
                        <li><a href="<?=$this->baseUrl('public/rules')?>">Regolamento</a></li>
                        <li><a href="<?=$this->baseUrl('public/catalog')?>">Catalogo</a></li>
                        <li><a href="<?=$this->baseUrl('public/faq')?>">Faq</a></li>
                        <li><a href="<?=$this->baseUrl('public/login')?>">Accesso</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="app-content">
            <?=$this->layout()->content;?>
        </div>

        <div class="navbar navbar-default app-footer">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="<?=$this->baseUrl('public/aboutus')?>">Chi Siamo</a></li>
                        <li><a href="<?=$this->baseUrl('public/contacts')?>">Contattaci</a></li>
                        <li><a href="<?=$this->baseUrl('public/rules')?>">Regolamento</a></li>
                        <li><a href="<?=$this->baseUrl('public/faq')?>">Faq</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>