<?= $this->doctype();?>

<html>
    <head>
        <?= $this->headMeta(); ?>
        <?= $this->headLink(); ?>
        <?= $this->headTitle(); ?>
        <?= $this->headScript(); ?>
    </head>
    <body>
        
    <div class="navbar navbar-default app-header">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                            aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <img src="<?=$this->baseUrl($this->app->image->brand)?>" alt="Car Rental" />
                    </a>
                    <p class="navbar-text app-brand-text"><?=$this->app->NomeAzienda?></p>
                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?=$this->baseUrl('user/' . $this->app->url->home)?>">Home</a></li>
                        <li><a href="<?=$this->baseUrl('user/' . $this->app->url->catalog)?>">Catalogo</a></li>
                        <li><a href="<?=$this->baseUrl('public/')?>">Esci</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="app-content">
            <?=$this->layout()->content;?>
        </div>

        <div class="navbar navbar-default app-footer">
            <div class="container-fluid">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?=$this->baseUrl('user/' . $this->app->url->aboutus)?>">Chi Siamo</a></li>
                        <li><a href="<?=$this->baseUrl('user/' . $this->app->url->contacts)?>">Contattaci</a></li>
                        <li><a href="<?=$this->baseUrl('user/' . $this->app->url->rules)?>">Regolamento</a></li>
                        <li><a href="<?=$this->baseUrl('user/' . $this->app->url->faq)?>">Faq</a></li>
                    </ul>
                </div>
            </div>
        </div>


        <?=$this->render('_messanger.phtml')?>

    </body>
</html>