<div align="center">
    <h1><b>Su di noi</b></h1>
            <h3>Dove è iniziato il nostro viaggio</h3>
        <p>Nel 1946 la nostra azienda ha aperto il primo autonoleggio nell’aeroporto di Willow Run, a Detroit, con una flotta di ben 3 auto. Oggi Avis è attiva in oltre 5.000 località distribuite in 165 Paesi nel mondo.
Il nostro è un marchio pluri premiato che vanta una lunga storia di innovazioni nel settore dell’autonoleggio, ed è anche uno dei brand più performanti in termini di fedeltà e soddisfazione del cliente, grazie al suo impegno costante per fornire il massimo comfort e un servizio di alta qualità.
        </p>
</div>
<div>
    <br>
        <h4 align="center">La nostra storia è stata scandita da diversi avvenimenti importanti:</h4>
        <ul>
            <li><b>1946</b> La nostra azienda apre il primo autonoleggio presso l’aeroporto di Willow Run, a Detroit. Anticipando quella che sarebbe stata la tendenza nel periodo post-bellico, questo fu il primo autonoleggio con sede aeroportuale.</li>
            <li><b>1953</b> Inizia il processo di espansione internazionale con franchising in Europa, Canada e Messico.</li>
            <li><b>1963</b> La nostra azienda lancia una nuova audace campagna pubblicitaria… “We’re only No.2. We try harder”… questo slogan è ora annoverato fra i 10 migliori di sempre ed è stato assorbito come quintessenza della nostra cultura aziendale.</li>
            <li><b>1986</b> La nostra azienda diventa la prima società di autonoleggio della storia a fare il suo ingresso trionfale nella Borsa di Londra. Dopo i primi 3 anni come società pubblica, la nostra azienda triplica il suo valore di mercato.</li>
            <li><b>2003</b> Otteniamo il diritto di operare con il marchio Budget in Europa, Africa e Medio Oriente.</li>
            <li><b>2012</b> Riceve il premio “World’s Leading Business Car Rental Company” per il settimo anno consecutivo in occasione dei World Travel Awards.</li>
        </ul>
        <div>
            <table border align="center" style="text-align: center; font-size: 60pt;"><tr><td>IMMAGINE</td></tr></table>
        </div>
</div>

