<?php $this->headScript()->captureStart() ?>
    $(function(){
	var actionUrl = '<?= $this->url(array('controller' => 'api', 'action' => 'useredituservalidation',), 'default'); ?>';
	var formName = '<?= $this->profileForm->getName() ?>';
	$(":input").on('blur', function(event) {
            var formElementId = $(this).attr('id');
            doValidation(formElementId, actionUrl, formName);
        });
    });
<?php $this->headScript()->captureEnd() ?>

<div class="row">
    <div class="col-md-12"><h2>Profilo</h2></div>
    <div class="col-md-4"><b>Username:</b></div><div class="col-md-8"><?= $this->user->Username?></div>
    <div class="col-md-4"><b>Nome:</b></div><div class="col-md-8"><?= $this->user->Nome?></div>
    <div class="col-md-4"><b>Cognome:</b></div><div class="col-md-8"><?= $this->user->Cognome?></div>
    <div class="col-md-4"><b>Residenza:</b></div><div class="col-md-8"><?= $this->user->Residenza?></div>
    <div class="col-md-4"><b>Data di Nascita:</b></div><div class="col-md-8"><?=date('d/m/Y', strtotime($this->user->Nascita))?></div>
    <div class="col-md-4"><b>Occupazione:</b></div><div class="col-md-8"><?= $this->user->OccupazioneNome?></div>
</div>
<?=$this->profileForm->render()?>
<?php if($this->success){ ?>
    <div class="alert alert-success" role="alert"><?=$this->success?></div>
<?php } ?>

<h3>Storico Noleggi:</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Marca</th>
      <th scope="col">Modello</th>
      <th scope="col">Targa</th>
      <th scope="col">Inizio</th>
      <th scope="col">Fine</th>     
    </tr>
  </thead>
  <tbody>
<?php foreach($this->noleggiList as $i=>$nl){ ?>
    <tr>
      <td><?=($i+1)?></td>
      <td><?=$nl->Marca?></td>
      <td><?=$nl->Modello?></td>
      <td><?=$nl->TARGA?></td>
      <td><?=date('d/m/Y', strtotime($nl->Inizio))?></td>
      <td><?=date('d/m/Y', strtotime($nl->Fine))?></td>
    </tr>
</tbody>
<?php } ?>
</table>