<?php $this->headScript()->captureStart() ?>
    $(function(){
	var actionUrl = '<?= $this->url(array('controller' => 'api', 'action' => 'newuservalidation',), 'default'); ?>';
	var formName = '<?= $this->createForm->getName() ?>';
	$(":input").on('blur', function(event) {
            var formElementId = $(this).attr('id');
            doValidation(formElementId, actionUrl, formName);
        });
    });
<?php $this->headScript()->captureEnd() ?>

<h1>Crea Utente</h1>
<h4>Nuovo Utente:</h4>
<?=$this->createForm->render()?>
<div align='center'> <a href="<?=$this->baseUrl($this->layout . '/users')?>">Indietro</a></div>
<?php if($this->error){ ?>
<div class="alert alert-danger"><h3><?=$this->error?></h3></div>
<?php } ?>