<?php $this->headScript()->captureStart() ?>
    $(function(){
	var actionUrl = '<?= $this->url(array('controller' => 'api', 'action' => 'editfaqvalidation',), 'default'); ?>';
	var formName = '<?= $this->editForm2->getName() ?>';
	$(":input").on('blur', function(event) {
            var formElementId = $(this).attr('id');
            doValidation(formElementId, actionUrl, formName);
        });
    });
<?php $this->headScript()->captureEnd() ?>


<h1>Modifica Faq</h1>
<?php if($this->error){ ?>

<div class="alert alert-danger"><h3><?=$this->error?></h3></div>

<?php } else { ?>
    <h4>Faq: <?=$this->editFaq->ID?></h4>
    <?=$this->editForm2?>
    <div align='center'> <a href="<?=$this->baseUrl($this->layout . '/faq')?>">Indietro</a></div>

<?php } ?>