<?php $this->headScript()->captureStart() ?>
    $(function(){
	var actionUrl = '<?= $this->url(array('controller' => 'api', 'action' => 'edituservalidation',), 'default'); ?>';
	var formName = '<?= $this->editForm->getName() ?>';
	$(":input").on('blur', function(event) {
            var formElementId = $(this).attr('id');
            doValidation(formElementId, actionUrl, formName);
        });
    });
<?php $this->headScript()->captureEnd() ?>

    
<h1>Modifica Utente</h1>
<?php if($this->error){ ?>

<div class="alert alert-danger"><h3><?=$this->error?></h3></div>
<a href="<?=$this->baseUrl('admin/users')?>">Indietro</a>
<?php } else { ?>
    <h4>Utente: <?=$this->editUser->Username?></h4>

    <br>
    <?=$this->editForm->render()?>
    <div align='center'> <a href="<?=$this->baseUrl($this->layout . '/users')?>">Indietro</a></div>


<?php } ?>