<table>
    <thead><th>Mese</th><th>Auto Noleggiate</th></thead>
    <tbody>
    <?php foreach($this->prospettoMese as $mese){?>
        <tr>
            <td><?=$this->mesi[$mese->Mese]?></td>
            <td><?=$mese->Conteggio?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<table>
    <thead><th>Anno</th><th>Auto Noleggiate</th></thead>
    <tbody>
    <?php foreach($this->prospettoAnno as $anno){?>
        <tr>
            <td><?=$anno->Anno?></td>
            <td><?=$anno->Conteggio?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>