<h1>Utenti</h1>


<button class="btn btn-success" onclick="window.location = '<?=$this->baseUrl('admin/createuser')?>'">
<i class="fas fa-plus"></i>
 Crea Utente
</button>
<table border>
    <thead>
        <th>Username</th>
        <th>Nome</th>
        <th>Cognome</th>
        <th>Password</th>
        <th>Email</th>
        <th>Residenza</th>
        <th>Nascita</th>
        <th>Ruolo</th>
        <th>Occupazione</th>
        <th>Modifica</th>
        <th>Elimina</th>
    </thead>
    <tbody>
        <?php foreach($this->users as $user){ ?>
        <tr>
            <td><?=$user['Username']?></td>
            <td><?=$user['Nome']?></td>
            <td><?=$user['Cognome']?></td>
            <td><?=$user['Password']?></td>
            <td><?=$user['Email']?></td>
            <td><?=$user['Residenza']?></td>
            <td><?=$user['Nascita']?></td>
            <td><?=$user['RuoloTesto']?></td>
            <td><?=$user['OccupazioneTesto']?></td>
            <td>
                <button class="btn btn-primary" onclick="window.location = '<?=$this->baseUrl('admin/edituser/id/' . $user['ID'])?>'">
                    <i class="fas fa-pen"></i>
                </button>
            </td>
            <td>
                <button <?=$user['ID'] == $this->user->ID ? 'disabled="true"' : ''?> class="btn btn-danger" onclick="if(window.confirm('Sei sicuro di vole eliminare l\'utente <?=$user['Username']?>')){ window.location = '<?=$this->baseUrl('admin/deleteuser/id/' . $user['ID'])?>' }">
                    <i class="fas fa-trash"></i>
                </button>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>